# Generated by Django 3.0.6 on 2020-09-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20200911_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='board_url_name',
            field=models.SlugField(unique=True),
        ),
    ]
