# Generated by Django 3.0.6 on 2020-09-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usingform', '0005_auto_20200728_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultform',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
