# Generated by Django 3.0.6 on 2020-10-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usingform', '0007_auto_20201010_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultform',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defaultform',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
